repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [commit]
        args: ['.', '--check-only', '--profile=black']

      - id: black
        name: black
        language: system
        entry: black
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [commit]
        args: ['.', '--check']

      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [commit]
        entry: env TESTING=1 pytest
