version: '3'

volumes:
  redis:
  rethinkdb:

services:

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data
  
  rethinkdb:
    image: rethinkdb
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - rethinkdb:/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rethinkdb
  
  worker:
    build: .
    depends_on:
      - redis
      - rethinkdb
    entrypoint: rq worker tasks -u redis://redis:6379
    environment:
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
